export enum TipoTransacao {
  CREDITO = 'CREDITO',
  DEBITO = 'DEBITO',
  TRANSFERENCIA_SAIDA = 'TRANSFERENCIA_SAIDA',
  TRANSFERENCIA_ENTRADA = 'TRANSFERENCIA_ENTRADA',
  PAGAMENTO_FATURA = 'PAGAMENTO_FATURA'
}